python3 exercise_detection_mk5.py --learning_rate 0.005 --epochs 1000 --activation Tanh --regularization L2 --label test1 --arch method1 --position --regularization_rate 0.1
python3 exercise_detection_mk5.py --learning_rate 0.005 --epochs 1000 --activation Tanh --regularization L2 --label test1 --arch method1 --position --regularization_rate 0.01
python3 exercise_detection_mk5.py --learning_rate 0.005 --epochs 1000 --activation Tanh --regularization L2 --label test1 --arch method1 --position --regularization_rate 0.001
python3 exercise_detection_mk5.py --learning_rate 0.001 --epochs 1000 --activation Tanh --regularization L2 --label test1 --arch method1 --position --regularization_rate 0.1
python3 exercise_detection_mk5.py --learning_rate 0.001 --epochs 1000 --activation Tanh --regularization L2 --label test1 --arch method1 --position --regularization_rate 0.01
python3 exercise_detection_mk5.py --learning_rate 0.001 --epochs 1000 --activation Tanh --regularization L2 --label test1 --arch method1 --position --regularization_rate 0.001
python3 exercise_detection_mk5.py --learning_rate 0.0005 --epochs 1000 --activation Tanh --regularization L2 --label test1 --arch method1 --position --regularization_rate 0.1
python3 exercise_detection_mk5.py --learning_rate 0.0005 --epochs 1000 --activation Tanh --regularization L2 --label test1 --arch method1 --position --regularization_rate 0.01
python3 exercise_detection_mk5.py --learning_rate 0.0005 --epochs 1000 --activation Tanh --regularization L2 --label test1 --arch method1 --position --regularization_rate 0.001
python3 exercise_detection_mk5.py --learning_rate 0.5 --epochs 1000 --activation Relu --regularization L2 --label test1 --arch method1 --position --regularization_rate 0.1
python3 exercise_detection_mk5.py --learning_rate 0.5 --epochs 1000 --activation Relu --regularization L2 --label test1 --arch method1 --position --regularization_rate 0.01
python3 exercise_detection_mk5.py --learning_rate 0.5 --epochs 1000 --activation Relu --regularization L2 --label test1 --arch method1 --position --regularization_rate 0.001
python3 exercise_detection_mk5.py --learning_rate 0.1 --epochs 1000 --activation Relu --regularization L2 --label test1 --arch method1 --position --regularization_rate 0.1
python3 exercise_detection_mk5.py --learning_rate 0.1 --epochs 1000 --activation Relu --regularization L2 --label test1 --arch method1 --position --regularization_rate 0.01
python3 exercise_detection_mk5.py --learning_rate 0.1 --epochs 1000 --activation Relu --regularization L2 --label test1 --arch method1 --position --regularization_rate 0.001
python3 exercise_detection_mk5.py --learning_rate 0.05 --epochs 1000 --activation Relu --regularization L2 --label test1 --arch method1 --position --regularization_rate 0.1
python3 exercise_detection_mk5.py --learning_rate 0.05 --epochs 1000 --activation Relu --regularization L2 --label test1 --arch method1 --position --regularization_rate 0.01
python3 exercise_detection_mk5.py --learning_rate 0.05 --epochs 1000 --activation Relu --regularization L2 --label test1 --arch method1 --position --regularization_rate 0.001
python3 exercise_detection_mk5.py --learning_rate 0.05 --epochs 1000 --activation Sigmoid --regularization L2 --label test1 --arch method1 --position --regularization_rate 0.1
python3 exercise_detection_mk5.py --learning_rate 0.05 --epochs 1000 --activation Sigmoid --regularization L2 --label test1 --arch method1 --position --regularization_rate 0.01
python3 exercise_detection_mk5.py --learning_rate 0.05 --epochs 1000 --activation Sigmoid --regularization L2 --label test1 --arch method1 --position --regularization_rate 0.001
python3 exercise_detection_mk5.py --learning_rate 0.01 --epochs 1000 --activation Sigmoid --regularization L2 --label test1 --arch method1 --position --regularization_rate 0.1
python3 exercise_detection_mk5.py --learning_rate 0.01 --epochs 1000 --activation Sigmoid --regularization L2 --label test1 --arch method1 --position --regularization_rate 0.01
python3 exercise_detection_mk5.py --learning_rate 0.01 --epochs 1000 --activation Sigmoid --regularization L2 --label test1 --arch method1 --position --regularization_rate 0.001
python3 exercise_detection_mk5.py --learning_rate 0.005 --epochs 1000 --activation Sigmoid --regularization L2 --label test1 --arch method1 --position --regularization_rate 0.1
python3 exercise_detection_mk5.py --learning_rate 0.005 --epochs 1000 --activation Sigmoid --regularization L2 --label test1 --arch method1 --position --regularization_rate 0.01
python3 exercise_detection_mk5.py --learning_rate 0.005 --epochs 1000 --activation Sigmoid --regularization L2 --label test1 --arch method1 --position --regularization_rate 0.001
python3 exercise_detection_mk5.py --learning_rate 0.005 --epochs 1000 --activation Sigmoid --regularization L2 --label test1 --arch method3 --position --regularization_rate 0.1
python3 exercise_detection_mk5.py --learning_rate 0.005 --epochs 1000 --activation Sigmoid --regularization L2 --label test1 --arch method3 --position --regularization_rate 0.01
python3 exercise_detection_mk5.py --learning_rate 0.005 --epochs 1000 --activation Sigmoid --regularization L2 --label test1 --arch method3 --position --regularization_rate 0.001
python3 exercise_detection_mk5.py --learning_rate 0.001 --epochs 1000 --activation Sigmoid --regularization L2 --label test1 --arch method3 --position --regularization_rate 0.1
python3 exercise_detection_mk5.py --learning_rate 0.001 --epochs 1000 --activation Sigmoid --regularization L2 --label test1 --arch method3 --position --regularization_rate 0.01
python3 exercise_detection_mk5.py --learning_rate 0.001 --epochs 1000 --activation Sigmoid --regularization L2 --label test1 --arch method3 --position --regularization_rate 0.001
python3 exercise_detection_mk5.py --learning_rate 0.0005 --epochs 1000 --activation Sigmoid --regularization L2 --label test1 --arch method3 --position --regularization_rate 0.1
python3 exercise_detection_mk5.py --learning_rate 0.0005 --epochs 1000 --activation Sigmoid --regularization L2 --label test1 --arch method3 --position --regularization_rate 0.01
python3 exercise_detection_mk5.py --learning_rate 0.0005 --epochs 1000 --activation Sigmoid --regularization L2 --label test1 --arch method3 --position --regularization_rate 0.001

python3 exercise_detection_mk5.py --learning_rate 0.005 --epochs 1000 --activation Tanh --regularization L2 --label test2 --arch method1 --position --regularization_rate 0.1
python3 exercise_detection_mk5.py --learning_rate 0.005 --epochs 1000 --activation Tanh --regularization L2 --label test2 --arch method1 --position --regularization_rate 0.01
python3 exercise_detection_mk5.py --learning_rate 0.005 --epochs 1000 --activation Tanh --regularization L2 --label test2 --arch method1 --position --regularization_rate 0.001
python3 exercise_detection_mk5.py --learning_rate 0.001 --epochs 1000 --activation Tanh --regularization L2 --label test2 --arch method1 --position --regularization_rate 0.1
python3 exercise_detection_mk5.py --learning_rate 0.001 --epochs 1000 --activation Tanh --regularization L2 --label test2 --arch method1 --position --regularization_rate 0.01
python3 exercise_detection_mk5.py --learning_rate 0.001 --epochs 1000 --activation Tanh --regularization L2 --label test2 --arch method1 --position --regularization_rate 0.001
python3 exercise_detection_mk5.py --learning_rate 0.0005 --epochs 1000 --activation Tanh --regularization L2 --label test2 --arch method1 --position --regularization_rate 0.1
python3 exercise_detection_mk5.py --learning_rate 0.0005 --epochs 1000 --activation Tanh --regularization L2 --label test2 --arch method1 --position --regularization_rate 0.01
python3 exercise_detection_mk5.py --learning_rate 0.0005 --epochs 1000 --activation Tanh --regularization L2 --label test2 --arch method1 --position --regularization_rate 0.001
python3 exercise_detection_mk5.py --learning_rate 0.5 --epochs 1000 --activation Relu --regularization L2 --label test2 --arch method1 --position --regularization_rate 0.1
python3 exercise_detection_mk5.py --learning_rate 0.5 --epochs 1000 --activation Relu --regularization L2 --label test2 --arch method1 --position --regularization_rate 0.01
python3 exercise_detection_mk5.py --learning_rate 0.5 --epochs 1000 --activation Relu --regularization L2 --label test2 --arch method1 --position --regularization_rate 0.001
python3 exercise_detection_mk5.py --learning_rate 0.1 --epochs 1000 --activation Relu --regularization L2 --label test2 --arch method1 --position --regularization_rate 0.1
python3 exercise_detection_mk5.py --learning_rate 0.1 --epochs 1000 --activation Relu --regularization L2 --label test2 --arch method1 --position --regularization_rate 0.01
python3 exercise_detection_mk5.py --learning_rate 0.1 --epochs 1000 --activation Relu --regularization L2 --label test2 --arch method1 --position --regularization_rate 0.001
python3 exercise_detection_mk5.py --learning_rate 0.05 --epochs 1000 --activation Relu --regularization L2 --label test2 --arch method1 --position --regularization_rate 0.1
python3 exercise_detection_mk5.py --learning_rate 0.05 --epochs 1000 --activation Relu --regularization L2 --label test2 --arch method1 --position --regularization_rate 0.01
python3 exercise_detection_mk5.py --learning_rate 0.05 --epochs 1000 --activation Relu --regularization L2 --label test2 --arch method1 --position --regularization_rate 0.001
python3 exercise_detection_mk5.py --learning_rate 0.05 --epochs 1000 --activation Sigmoid --regularization L2 --label test2 --arch method1 --position --regularization_rate 0.1
python3 exercise_detection_mk5.py --learning_rate 0.05 --epochs 1000 --activation Sigmoid --regularization L2 --label test2 --arch method1 --position --regularization_rate 0.01
python3 exercise_detection_mk5.py --learning_rate 0.05 --epochs 1000 --activation Sigmoid --regularization L2 --label test2 --arch method1 --position --regularization_rate 0.001
python3 exercise_detection_mk5.py --learning_rate 0.01 --epochs 1000 --activation Sigmoid --regularization L2 --label test2 --arch method1 --position --regularization_rate 0.1
python3 exercise_detection_mk5.py --learning_rate 0.01 --epochs 1000 --activation Sigmoid --regularization L2 --label test2 --arch method1 --position --regularization_rate 0.01
python3 exercise_detection_mk5.py --learning_rate 0.01 --epochs 1000 --activation Sigmoid --regularization L2 --label test2 --arch method1 --position --regularization_rate 0.001
python3 exercise_detection_mk5.py --learning_rate 0.005 --epochs 1000 --activation Sigmoid --regularization L2 --label test2 --arch method1 --position --regularization_rate 0.1
python3 exercise_detection_mk5.py --learning_rate 0.005 --epochs 1000 --activation Sigmoid --regularization L2 --label test2 --arch method1 --position --regularization_rate 0.01
python3 exercise_detection_mk5.py --learning_rate 0.005 --epochs 1000 --activation Sigmoid --regularization L2 --label test2 --arch method1 --position --regularization_rate 0.001
python3 exercise_detection_mk5.py --learning_rate 0.005 --epochs 1000 --activation Sigmoid --regularization L2 --label test2 --arch method3 --position --regularization_rate 0.1
python3 exercise_detection_mk5.py --learning_rate 0.005 --epochs 1000 --activation Sigmoid --regularization L2 --label test2 --arch method3 --position --regularization_rate 0.01
python3 exercise_detection_mk5.py --learning_rate 0.005 --epochs 1000 --activation Sigmoid --regularization L2 --label test2 --arch method3 --position --regularization_rate 0.001
python3 exercise_detection_mk5.py --learning_rate 0.001 --epochs 1000 --activation Sigmoid --regularization L2 --label test2 --arch method3 --position --regularization_rate 0.1
python3 exercise_detection_mk5.py --learning_rate 0.001 --epochs 1000 --activation Sigmoid --regularization L2 --label test2 --arch method3 --position --regularization_rate 0.01
python3 exercise_detection_mk5.py --learning_rate 0.001 --epochs 1000 --activation Sigmoid --regularization L2 --label test2 --arch method3 --position --regularization_rate 0.001
python3 exercise_detection_mk5.py --learning_rate 0.0005 --epochs 1000 --activation Sigmoid --regularization L2 --label test2 --arch method3 --position --regularization_rate 0.1
python3 exercise_detection_mk5.py --learning_rate 0.0005 --epochs 1000 --activation Sigmoid --regularization L2 --label test2 --arch method3 --position --regularization_rate 0.01
python3 exercise_detection_mk5.py --learning_rate 0.0005 --epochs 1000 --activation Sigmoid --regularization L2 --label test2 --arch method3 --position --regularization_rate 0.001

python3 exercise_detection_mk5.py --learning_rate 0.005 --epochs 1000 --activation Tanh --regularization L2 --label test3 --arch method1 --position --regularization_rate 0.1
python3 exercise_detection_mk5.py --learning_rate 0.005 --epochs 1000 --activation Tanh --regularization L2 --label test3 --arch method1 --position --regularization_rate 0.01
python3 exercise_detection_mk5.py --learning_rate 0.005 --epochs 1000 --activation Tanh --regularization L2 --label test3 --arch method1 --position --regularization_rate 0.001
python3 exercise_detection_mk5.py --learning_rate 0.001 --epochs 1000 --activation Tanh --regularization L2 --label test3 --arch method1 --position --regularization_rate 0.1
python3 exercise_detection_mk5.py --learning_rate 0.001 --epochs 1000 --activation Tanh --regularization L2 --label test3 --arch method1 --position --regularization_rate 0.01
python3 exercise_detection_mk5.py --learning_rate 0.001 --epochs 1000 --activation Tanh --regularization L2 --label test3 --arch method1 --position --regularization_rate 0.001
python3 exercise_detection_mk5.py --learning_rate 0.0005 --epochs 1000 --activation Tanh --regularization L2 --label test3 --arch method1 --position --regularization_rate 0.1
python3 exercise_detection_mk5.py --learning_rate 0.0005 --epochs 1000 --activation Tanh --regularization L2 --label test3 --arch method1 --position --regularization_rate 0.01
python3 exercise_detection_mk5.py --learning_rate 0.0005 --epochs 1000 --activation Tanh --regularization L2 --label test3 --arch method1 --position --regularization_rate 0.001
python3 exercise_detection_mk5.py --learning_rate 0.5 --epochs 1000 --activation Relu --regularization L2 --label test3 --arch method1 --position --regularization_rate 0.1
python3 exercise_detection_mk5.py --learning_rate 0.5 --epochs 1000 --activation Relu --regularization L2 --label test3 --arch method1 --position --regularization_rate 0.01
python3 exercise_detection_mk5.py --learning_rate 0.5 --epochs 1000 --activation Relu --regularization L2 --label test3 --arch method1 --position --regularization_rate 0.001
python3 exercise_detection_mk5.py --learning_rate 0.1 --epochs 1000 --activation Relu --regularization L2 --label test3 --arch method1 --position --regularization_rate 0.1
python3 exercise_detection_mk5.py --learning_rate 0.1 --epochs 1000 --activation Relu --regularization L2 --label test3 --arch method1 --position --regularization_rate 0.01
python3 exercise_detection_mk5.py --learning_rate 0.1 --epochs 1000 --activation Relu --regularization L2 --label test3 --arch method1 --position --regularization_rate 0.001
python3 exercise_detection_mk5.py --learning_rate 0.05 --epochs 1000 --activation Relu --regularization L2 --label test3 --arch method1 --position --regularization_rate 0.1
python3 exercise_detection_mk5.py --learning_rate 0.05 --epochs 1000 --activation Relu --regularization L2 --label test3 --arch method1 --position --regularization_rate 0.01
python3 exercise_detection_mk5.py --learning_rate 0.05 --epochs 1000 --activation Relu --regularization L2 --label test3 --arch method1 --position --regularization_rate 0.001
python3 exercise_detection_mk5.py --learning_rate 0.05 --epochs 1000 --activation Sigmoid --regularization L2 --label test3 --arch method1 --position --regularization_rate 0.1
python3 exercise_detection_mk5.py --learning_rate 0.05 --epochs 1000 --activation Sigmoid --regularization L2 --label test3 --arch method1 --position --regularization_rate 0.01
python3 exercise_detection_mk5.py --learning_rate 0.05 --epochs 1000 --activation Sigmoid --regularization L2 --label test3 --arch method1 --position --regularization_rate 0.001
python3 exercise_detection_mk5.py --learning_rate 0.01 --epochs 1000 --activation Sigmoid --regularization L2 --label test3 --arch method1 --position --regularization_rate 0.1
python3 exercise_detection_mk5.py --learning_rate 0.01 --epochs 1000 --activation Sigmoid --regularization L2 --label test3 --arch method1 --position --regularization_rate 0.01
python3 exercise_detection_mk5.py --learning_rate 0.01 --epochs 1000 --activation Sigmoid --regularization L2 --label test3 --arch method1 --position --regularization_rate 0.001
python3 exercise_detection_mk5.py --learning_rate 0.005 --epochs 1000 --activation Sigmoid --regularization L2 --label test3 --arch method1 --position --regularization_rate 0.1
python3 exercise_detection_mk5.py --learning_rate 0.005 --epochs 1000 --activation Sigmoid --regularization L2 --label test3 --arch method1 --position --regularization_rate 0.01
python3 exercise_detection_mk5.py --learning_rate 0.005 --epochs 1000 --activation Sigmoid --regularization L2 --label test3 --arch method1 --position --regularization_rate 0.001
python3 exercise_detection_mk5.py --learning_rate 0.005 --epochs 1000 --activation Sigmoid --regularization L2 --label test3 --arch method3 --position --regularization_rate 0.1
python3 exercise_detection_mk5.py --learning_rate 0.005 --epochs 1000 --activation Sigmoid --regularization L2 --label test3 --arch method3 --position --regularization_rate 0.01
python3 exercise_detection_mk5.py --learning_rate 0.005 --epochs 1000 --activation Sigmoid --regularization L2 --label test3 --arch method3 --position --regularization_rate 0.001
python3 exercise_detection_mk5.py --learning_rate 0.001 --epochs 1000 --activation Sigmoid --regularization L2 --label test3 --arch method3 --position --regularization_rate 0.1
python3 exercise_detection_mk5.py --learning_rate 0.001 --epochs 1000 --activation Sigmoid --regularization L2 --label test3 --arch method3 --position --regularization_rate 0.01
python3 exercise_detection_mk5.py --learning_rate 0.001 --epochs 1000 --activation Sigmoid --regularization L2 --label test3 --arch method3 --position --regularization_rate 0.001
python3 exercise_detection_mk5.py --learning_rate 0.0005 --epochs 1000 --activation Sigmoid --regularization L2 --label test3 --arch method3 --position --regularization_rate 0.1
python3 exercise_detection_mk5.py --learning_rate 0.0005 --epochs 1000 --activation Sigmoid --regularization L2 --label test3 --arch method3 --position --regularization_rate 0.01
python3 exercise_detection_mk5.py --learning_rate 0.0005 --epochs 1000 --activation Sigmoid --regularization L2 --label test3 --arch method3 --position --regularization_rate 0.001

python3 writingIntoExcelFinalTests.py